/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeoIndexRouteImport } from './routes/seo/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as SeoWriteRouteImport } from './routes/seo/write'
import { Route as SeoScrubRouteImport } from './routes/seo/scrub'
import { Route as SeoRewriteRouteImport } from './routes/seo/rewrite'
import { Route as SeoResearchRouteImport } from './routes/seo/research'
import { Route as SeoPerformanceRouteImport } from './routes/seo/performance'
import { Route as SeoOptimizeRouteImport } from './routes/seo/optimize'
import { Route as SeoAnalyzeRouteImport } from './routes/seo/analyze'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiGscCallbackRouteImport } from './routes/api/gsc-callback'
import { Route as DashboardSeoPlannerIndexRouteImport } from './routes/dashboard/seo-planner/index'
import { Route as DashboardSeoPlannerSettingsRouteImport } from './routes/dashboard/seo-planner/settings'
import { Route as DashboardSeoPlannerQueueRouteImport } from './routes/dashboard/seo-planner/queue'
import { Route as DashboardSeoPlannerOpportunitiesRouteImport } from './routes/dashboard/seo-planner/opportunities'
import { Route as DashboardSeoPlannerIdeateRouteImport } from './routes/dashboard/seo-planner/ideate'
import { Route as DashboardPageEditorSlugRouteImport } from './routes/dashboard/page-editor.$slug'
import { Route as DashboardEditorSlugRouteImport } from './routes/dashboard/editor.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoIndexRoute = SeoIndexRouteImport.update({
  id: '/seo/',
  path: '/seo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoWriteRoute = SeoWriteRouteImport.update({
  id: '/seo/write',
  path: '/seo/write',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoScrubRoute = SeoScrubRouteImport.update({
  id: '/seo/scrub',
  path: '/seo/scrub',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRewriteRoute = SeoRewriteRouteImport.update({
  id: '/seo/rewrite',
  path: '/seo/rewrite',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoResearchRoute = SeoResearchRouteImport.update({
  id: '/seo/research',
  path: '/seo/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoPerformanceRoute = SeoPerformanceRouteImport.update({
  id: '/seo/performance',
  path: '/seo/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoOptimizeRoute = SeoOptimizeRouteImport.update({
  id: '/seo/optimize',
  path: '/seo/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAnalyzeRoute = SeoAnalyzeRouteImport.update({
  id: '/seo/analyze',
  path: '/seo/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGscCallbackRoute = ApiGscCallbackRouteImport.update({
  id: '/api/gsc-callback',
  path: '/api/gsc-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSeoPlannerIndexRoute =
  DashboardSeoPlannerIndexRouteImport.update({
    id: '/dashboard/seo-planner/',
    path: '/dashboard/seo-planner/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSeoPlannerSettingsRoute =
  DashboardSeoPlannerSettingsRouteImport.update({
    id: '/dashboard/seo-planner/settings',
    path: '/dashboard/seo-planner/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSeoPlannerQueueRoute =
  DashboardSeoPlannerQueueRouteImport.update({
    id: '/dashboard/seo-planner/queue',
    path: '/dashboard/seo-planner/queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSeoPlannerOpportunitiesRoute =
  DashboardSeoPlannerOpportunitiesRouteImport.update({
    id: '/dashboard/seo-planner/opportunities',
    path: '/dashboard/seo-planner/opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSeoPlannerIdeateRoute =
  DashboardSeoPlannerIdeateRouteImport.update({
    id: '/dashboard/seo-planner/ideate',
    path: '/dashboard/seo-planner/ideate',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPageEditorSlugRoute = DashboardPageEditorSlugRouteImport.update({
  id: '/dashboard/page-editor/$slug',
  path: '/dashboard/page-editor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditorSlugRoute = DashboardEditorSlugRouteImport.update({
  id: '/dashboard/editor/$slug',
  path: '/dashboard/editor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/api/gsc-callback': typeof ApiGscCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/post/$slug': typeof PostSlugRoute
  '/seo/analyze': typeof SeoAnalyzeRoute
  '/seo/optimize': typeof SeoOptimizeRoute
  '/seo/performance': typeof SeoPerformanceRoute
  '/seo/research': typeof SeoResearchRoute
  '/seo/rewrite': typeof SeoRewriteRoute
  '/seo/scrub': typeof SeoScrubRoute
  '/seo/write': typeof SeoWriteRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/seo': typeof SeoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/editor/$slug': typeof DashboardEditorSlugRoute
  '/dashboard/page-editor/$slug': typeof DashboardPageEditorSlugRoute
  '/dashboard/seo-planner/ideate': typeof DashboardSeoPlannerIdeateRoute
  '/dashboard/seo-planner/opportunities': typeof DashboardSeoPlannerOpportunitiesRoute
  '/dashboard/seo-planner/queue': typeof DashboardSeoPlannerQueueRoute
  '/dashboard/seo-planner/settings': typeof DashboardSeoPlannerSettingsRoute
  '/dashboard/seo-planner': typeof DashboardSeoPlannerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/api/gsc-callback': typeof ApiGscCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/post/$slug': typeof PostSlugRoute
  '/seo/analyze': typeof SeoAnalyzeRoute
  '/seo/optimize': typeof SeoOptimizeRoute
  '/seo/performance': typeof SeoPerformanceRoute
  '/seo/research': typeof SeoResearchRoute
  '/seo/rewrite': typeof SeoRewriteRoute
  '/seo/scrub': typeof SeoScrubRoute
  '/seo/write': typeof SeoWriteRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/seo': typeof SeoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/editor/$slug': typeof DashboardEditorSlugRoute
  '/dashboard/page-editor/$slug': typeof DashboardPageEditorSlugRoute
  '/dashboard/seo-planner/ideate': typeof DashboardSeoPlannerIdeateRoute
  '/dashboard/seo-planner/opportunities': typeof DashboardSeoPlannerOpportunitiesRoute
  '/dashboard/seo-planner/queue': typeof DashboardSeoPlannerQueueRoute
  '/dashboard/seo-planner/settings': typeof DashboardSeoPlannerSettingsRoute
  '/dashboard/seo-planner': typeof DashboardSeoPlannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/api/gsc-callback': typeof ApiGscCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/post/$slug': typeof PostSlugRoute
  '/seo/analyze': typeof SeoAnalyzeRoute
  '/seo/optimize': typeof SeoOptimizeRoute
  '/seo/performance': typeof SeoPerformanceRoute
  '/seo/research': typeof SeoResearchRoute
  '/seo/rewrite': typeof SeoRewriteRoute
  '/seo/scrub': typeof SeoScrubRoute
  '/seo/write': typeof SeoWriteRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/seo/': typeof SeoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/editor/$slug': typeof DashboardEditorSlugRoute
  '/dashboard/page-editor/$slug': typeof DashboardPageEditorSlugRoute
  '/dashboard/seo-planner/ideate': typeof DashboardSeoPlannerIdeateRoute
  '/dashboard/seo-planner/opportunities': typeof DashboardSeoPlannerOpportunitiesRoute
  '/dashboard/seo-planner/queue': typeof DashboardSeoPlannerQueueRoute
  '/dashboard/seo-planner/settings': typeof DashboardSeoPlannerSettingsRoute
  '/dashboard/seo-planner/': typeof DashboardSeoPlannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/login'
    | '/api/gsc-callback'
    | '/blog/$slug'
    | '/dashboard/settings'
    | '/post/$slug'
    | '/seo/analyze'
    | '/seo/optimize'
    | '/seo/performance'
    | '/seo/research'
    | '/seo/rewrite'
    | '/seo/scrub'
    | '/seo/write'
    | '/blog'
    | '/dashboard'
    | '/seo'
    | '/api/auth/$'
    | '/dashboard/editor/$slug'
    | '/dashboard/page-editor/$slug'
    | '/dashboard/seo-planner/ideate'
    | '/dashboard/seo-planner/opportunities'
    | '/dashboard/seo-planner/queue'
    | '/dashboard/seo-planner/settings'
    | '/dashboard/seo-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/api/gsc-callback'
    | '/blog/$slug'
    | '/dashboard/settings'
    | '/post/$slug'
    | '/seo/analyze'
    | '/seo/optimize'
    | '/seo/performance'
    | '/seo/research'
    | '/seo/rewrite'
    | '/seo/scrub'
    | '/seo/write'
    | '/blog'
    | '/dashboard'
    | '/seo'
    | '/api/auth/$'
    | '/dashboard/editor/$slug'
    | '/dashboard/page-editor/$slug'
    | '/dashboard/seo-planner/ideate'
    | '/dashboard/seo-planner/opportunities'
    | '/dashboard/seo-planner/queue'
    | '/dashboard/seo-planner/settings'
    | '/dashboard/seo-planner'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/login'
    | '/api/gsc-callback'
    | '/blog/$slug'
    | '/dashboard/settings'
    | '/post/$slug'
    | '/seo/analyze'
    | '/seo/optimize'
    | '/seo/performance'
    | '/seo/research'
    | '/seo/rewrite'
    | '/seo/scrub'
    | '/seo/write'
    | '/blog/'
    | '/dashboard/'
    | '/seo/'
    | '/api/auth/$'
    | '/dashboard/editor/$slug'
    | '/dashboard/page-editor/$slug'
    | '/dashboard/seo-planner/ideate'
    | '/dashboard/seo-planner/opportunities'
    | '/dashboard/seo-planner/queue'
    | '/dashboard/seo-planner/settings'
    | '/dashboard/seo-planner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  LoginRoute: typeof LoginRoute
  ApiGscCallbackRoute: typeof ApiGscCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  PostSlugRoute: typeof PostSlugRoute
  SeoAnalyzeRoute: typeof SeoAnalyzeRoute
  SeoOptimizeRoute: typeof SeoOptimizeRoute
  SeoPerformanceRoute: typeof SeoPerformanceRoute
  SeoResearchRoute: typeof SeoResearchRoute
  SeoRewriteRoute: typeof SeoRewriteRoute
  SeoScrubRoute: typeof SeoScrubRoute
  SeoWriteRoute: typeof SeoWriteRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SeoIndexRoute: typeof SeoIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DashboardEditorSlugRoute: typeof DashboardEditorSlugRoute
  DashboardPageEditorSlugRoute: typeof DashboardPageEditorSlugRoute
  DashboardSeoPlannerIdeateRoute: typeof DashboardSeoPlannerIdeateRoute
  DashboardSeoPlannerOpportunitiesRoute: typeof DashboardSeoPlannerOpportunitiesRoute
  DashboardSeoPlannerQueueRoute: typeof DashboardSeoPlannerQueueRoute
  DashboardSeoPlannerSettingsRoute: typeof DashboardSeoPlannerSettingsRoute
  DashboardSeoPlannerIndexRoute: typeof DashboardSeoPlannerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/': {
      id: '/seo/'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/write': {
      id: '/seo/write'
      path: '/seo/write'
      fullPath: '/seo/write'
      preLoaderRoute: typeof SeoWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/scrub': {
      id: '/seo/scrub'
      path: '/seo/scrub'
      fullPath: '/seo/scrub'
      preLoaderRoute: typeof SeoScrubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/rewrite': {
      id: '/seo/rewrite'
      path: '/seo/rewrite'
      fullPath: '/seo/rewrite'
      preLoaderRoute: typeof SeoRewriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/research': {
      id: '/seo/research'
      path: '/seo/research'
      fullPath: '/seo/research'
      preLoaderRoute: typeof SeoResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/performance': {
      id: '/seo/performance'
      path: '/seo/performance'
      fullPath: '/seo/performance'
      preLoaderRoute: typeof SeoPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/optimize': {
      id: '/seo/optimize'
      path: '/seo/optimize'
      fullPath: '/seo/optimize'
      preLoaderRoute: typeof SeoOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/analyze': {
      id: '/seo/analyze'
      path: '/seo/analyze'
      fullPath: '/seo/analyze'
      preLoaderRoute: typeof SeoAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gsc-callback': {
      id: '/api/gsc-callback'
      path: '/api/gsc-callback'
      fullPath: '/api/gsc-callback'
      preLoaderRoute: typeof ApiGscCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seo-planner/': {
      id: '/dashboard/seo-planner/'
      path: '/dashboard/seo-planner'
      fullPath: '/dashboard/seo-planner'
      preLoaderRoute: typeof DashboardSeoPlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seo-planner/settings': {
      id: '/dashboard/seo-planner/settings'
      path: '/dashboard/seo-planner/settings'
      fullPath: '/dashboard/seo-planner/settings'
      preLoaderRoute: typeof DashboardSeoPlannerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seo-planner/queue': {
      id: '/dashboard/seo-planner/queue'
      path: '/dashboard/seo-planner/queue'
      fullPath: '/dashboard/seo-planner/queue'
      preLoaderRoute: typeof DashboardSeoPlannerQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seo-planner/opportunities': {
      id: '/dashboard/seo-planner/opportunities'
      path: '/dashboard/seo-planner/opportunities'
      fullPath: '/dashboard/seo-planner/opportunities'
      preLoaderRoute: typeof DashboardSeoPlannerOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seo-planner/ideate': {
      id: '/dashboard/seo-planner/ideate'
      path: '/dashboard/seo-planner/ideate'
      fullPath: '/dashboard/seo-planner/ideate'
      preLoaderRoute: typeof DashboardSeoPlannerIdeateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/page-editor/$slug': {
      id: '/dashboard/page-editor/$slug'
      path: '/dashboard/page-editor/$slug'
      fullPath: '/dashboard/page-editor/$slug'
      preLoaderRoute: typeof DashboardPageEditorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/editor/$slug': {
      id: '/dashboard/editor/$slug'
      path: '/dashboard/editor/$slug'
      fullPath: '/dashboard/editor/$slug'
      preLoaderRoute: typeof DashboardEditorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  LoginRoute: LoginRoute,
  ApiGscCallbackRoute: ApiGscCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  PostSlugRoute: PostSlugRoute,
  SeoAnalyzeRoute: SeoAnalyzeRoute,
  SeoOptimizeRoute: SeoOptimizeRoute,
  SeoPerformanceRoute: SeoPerformanceRoute,
  SeoResearchRoute: SeoResearchRoute,
  SeoRewriteRoute: SeoRewriteRoute,
  SeoScrubRoute: SeoScrubRoute,
  SeoWriteRoute: SeoWriteRoute,
  BlogIndexRoute: BlogIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SeoIndexRoute: SeoIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DashboardEditorSlugRoute: DashboardEditorSlugRoute,
  DashboardPageEditorSlugRoute: DashboardPageEditorSlugRoute,
  DashboardSeoPlannerIdeateRoute: DashboardSeoPlannerIdeateRoute,
  DashboardSeoPlannerOpportunitiesRoute: DashboardSeoPlannerOpportunitiesRoute,
  DashboardSeoPlannerQueueRoute: DashboardSeoPlannerQueueRoute,
  DashboardSeoPlannerSettingsRoute: DashboardSeoPlannerSettingsRoute,
  DashboardSeoPlannerIndexRoute: DashboardSeoPlannerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
